config/routes.rb
Rails.application.routes.draw do
  root 'chats#index'
  resources :chats, except: [:new, :show] do
    collection do
      post :confirm
      get :info
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
    validates :content, presence: true, length: { in:1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: [:edit, :update, :destroy]
  before_action :chats_order, only: [:index, :create, :update, :confirm]

  def index
    @chat = Chat.new
  end

  def info; end

  def create
    @chat = Chat.new(chat_params)
    if params[:back]
      render :index
    else
      if @chat.save
        redirect_to chats_path, notice: 'しゃべりました！'
      else
        render :index
      end
    end
  end

  def edit; end

  def update
    if params[:back]
      redirect_to chats_path
    else
      if set_chat.update(chat_params)
        redirect_to chats_path, notice: "しゃべりなおしました！"
      else
        render :edit
      end
    end
  end

  def destroy
    @chat.destroy
    redirect_to chats_path, notice: "発言を取り消しました"
  end

  def confirm
    @chat = Chat.new(chat_params)
    render :index if @chat.invalid?
  end

  private

  def chat_params
    params.require(:chat).permit(:title, :content)
  end

  def set_chat
    @chat = Chat.find(params[:id])
  end

  def chats_order
    @chats = Chat.order(id: :DESC)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
  def choose_index_or_edit
    if action_name == 'index' || action_name == 'create' || action_name == 'confirm'
      confirm_chats_path
    else action_name == 'edit'
      chat_path
    end
  end
end

app/views/chats/_form.html.erb
<%= form_with(model: @chat, local: true, url: choose_index_or_edit) do |form| %>
 <% if @chat.errors.any? %>
  <div id='error_explanation'>
    <h2><%= @chat.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% @chat.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class='form-group'>
    <p id='counter'>残り140文字</p>
    <%= form.text_area:'content', class:'form-control', id:'input-text', rows:3, placeholder:'なんでもしゃべって' %>
    <%= form.submit 'しゃべる', class:'post-btn btn-primary' %>
  </div>
<% end %>

app/views/chats/confirm.html.erb
<div class='container'>
  <h3>以下の内容で本当にささやいても良いですか？</h3>
  <%= form_with(model: @chat, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <p class='confirm-text'><%= @chat.content %></p>
  <div class='confirm-btns'>
    <%= form.submit 'しゃべる', class:'confirm-btn btn-primary' %>
    <%= form.submit 'だまる', name:'back', class:'confirm-btn btn-info' %>
  <% end %>
  </div>
</div>

app/views/chats/edit.html.erb
<div class='container'>
  <h2>つぶやきを編集する</h2>
  <%= form_with(model: @chat, local: true, url: choose_index_or_edit) do |form| %>
   <% if @chat.errors.any? %>
    <div id='error_explanation'>
      <h2><%= @chat.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @chat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class='form-group'>
      <p id='counter'>残り140文字</p>
      <%= form.text_area:'content', class:'form-control', id:'input-text', rows:3, placeholder:'なんでもしゃべって' %>
    <div class='edit-btns'>
      <%= form.submit 'しゃべる', class:'edit-btn btn-primary' %>
      <%= form.submit 'だまる', name:'back', class:'edit-btn btn-info'%>
    </div>
      <% end %>
  </div>
</div>

app/views/chats/index.html.erb
<div class='container'>
<%= form_with(model: @chat, local: true, url: choose_index_or_edit) do |form| %>
    <%= render 'form' %>
  <% end %>
  <div class='main'>
    <h4>おしゃべり一覧</h4>
    <p><%= notice %></p>
    <table class='table table-striped'>
    <% @chats.each do |chat| %>
      <tr>
        <th><%= chat.content %></th>
      </tr>
      <tr>
        <td>
          <div class='operate-btns'>
            <%= link_to 'しゃべりなおす', edit_chat_path(chat.id), class:'operate-btn btn-primary' %>
            <%= link_to '発言を取り消す', chat_path(chat.id), method: :delete, data: {confirm: '本当に取り消しますか？'}, class:'operate-btn btn-danger' %>
          </div>
        </td>
      </tr>
    <% end %>
    </table>
  </div>
</div>

app/views/chats/info.html.erb
<section class='info-header'>
  <h1 class="chatter-info">Chatterへようこそ！</h1>
</section>
<div class='container'>
  <section class='about'>
    <h1>アプリケーションについて</h1>
    <p>
    本アプリケーションは、DIVE INTO CODEの課題として、作成したTwitter-cloneです。<br>
    名前はなんとなくChatterにしてみましたが、<%= link_to '同名のサービス', 'https://www.salesforce.com/jp/products/chatter/overview/' %>がすでにありました笑。<br>
    しかも株式会社セールスフォース・ドットコムのサービスだったとは全くの勉強不足でした。お恥ずかしい。<br>
    </p>
    <p>
    肩肘張らずに気軽にチャットができるアプリとして活用いただければ嬉しく思います。<br>
    いずれにせよ人生初アプリなので、なんとなく愛着はあります笑。<br>
    </p>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name='viewport' content='width=device-width'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class='wrapper'>
      <nav class='navbar navbar-fixed-top'>
        <div class='container-fluid'>
          <div class='navbar-header'>
            <%= link_to 'Chatter !', chats_path, class:'navbar-brand' %>
            <ul class='nav navbar-nav'>
              <li><%= link_to 'TOP', chats_path %></li>
              <li><%= link_to 'INFO', info_chats_path %></li>
            </ul>
          </div>
        </div>
      </nav>
      <%= yield %>
      <footer>
        <p>2020年04月 森田 祥平 制作</p>
      </footer>
    </div>
  </body>
</html>